# Terminal
# See here: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
#if-shell "[ $(uname | grep 'Darwin') ]" 'set-option -g default-command "reattach-to-user-namespace -l zsh"'

# Correct terminal "identity"
set -g default-terminal "xterm-256color"

# Overrides default colors to get True Colour support
set-option -ga terminal-overrides ",xterm-256color:Tc"

# SOURCE: https://github.com/seebi/tmux-colors-solarized/blob/master/tmuxcolors-256.conf
#set-option -g status-bg colour235 #base02
#set-option -g status-fg colour136 #yellow
#set-option -g status-attr default

# Ctrl+A as PREFIX
set-option -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Keybindings
# set window split/new window at current path
unbind c
bind-key c new-window -c "#{pane_current_path}"
unbind '"'
unbind %
bind-key | split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"

# Pane movements
bind h select-pane -L
bind l select-pane -R
bind j select-pane -D
bind k select-pane -U

# New window with name
bind-key C command-prompt -p "Name of new window: " "new-window -n '%%'"

# Reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Vi copy-paste mode
set-window-option -g mode-keys vi
bind-key -Tcopy-mode-vi v send -X begin-selection; bind-key -Tcopy-mode-vi y send -X copy-selection-and-cancel # !!! only works for tmux > 2.4

set-window-option -g automatic-rename off # disable auto-rename when issuing a command
set-option -g allow-rename off

# Start numbering at 1
set -g base-index 1

# Allows for faster key repetition
set -s escape-time 0

# Rather than constraining window size to the maximum size of any client 
# connected to the *session*, constrain window size to the maximum size of any 
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize off

# Allows us to use C-a a <command> to send commands to a TMUX session inside 
# another TMUX session
bind-key a send-prefix

# Activity monitoring
setw -g monitor-activity on
set -g visual-activity on

# set to main-horizontal, 66% height for main pane
#bind m run-shell "~/.tmux/scripts/resize-adaptable.sh -l main-horizontal -p 66"
# Same thing for verical layouts
#bind M run-shell "~/.tmux/scripts/resize-adaptable.sh -l main-vertical -p 50"

# Disable mouse
set -g mouse off

# Plugin: tmux-resurrect to save and reload sessions and much more
# Check out https://github.com/tmux-plugins/tmux-resurrect
run-shell ~/.dotfiles/tmux/tmux-resurrect/resurrect.tmux
